### ISSUE TITLE
error with semicolons and multiline escaping

### ISSUE THREAD

**Issue by trevor** [TwP/inifile#17]
Valid:

``` ini
three   = hello \
multiline
```

Valid:

``` ini
three   = "hello; \
multiline"
```

Valid:

``` ini
three   = "hello;
multiline"
```

Invalid:

``` ini
three   = hello; \
multiline
```

**Comment by TwP** [comment]
The semicolon is considered a comment character by default. So the invalid case truly is invalid since the `\` character is part of the comment and it is not considered a newline continuation.

Your third case above is valid because the semicolon is inside a quoted string and not considered a comment character.

You can make that fourth case valid either by escaping the semicolon:

``` ini
three   = hello\; \
multiline
```

or by configuring the IniFile parser to treat semicolons as a regular character:

``` ruby
inifile = IniFile.new(:filename => "file.ini", :comment => "#")
```
